# -*- coding: utf-8 -*-
"""kasir makeupku

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XY1ekZq4UIHHH3y8fbZrpFLtmSPazkII
"""

# Aplikasi Kasir Sederhana (bisa dijalankan di Google Colab)

# Simpan daftar belanja
keranjang = []

def tambah_barang():
    nama = input("Masukkan nama barang: ")
    try:
        harga = float(input("Masukkan harga barang: "))
        jumlah = int(input("Masukkan jumlah barang: "))
        keranjang.append({'nama': nama, 'harga': harga, 'jumlah': jumlah})
        print(f"✅ Barang '{nama}' ditambahkan ke keranjang.")
    except ValueError:
        print("❌ Input harga atau jumlah tidak valid. Coba lagi.")

def tampilkan_keranjang():
    if not keranjang:
        print("⚠️  Keranjang masih kosong.")
        return
    print("\n📋 Daftar Belanja:")
    print("{:<20} {:<10} {:<10} {:<10}".format("Nama", "Harga", "Jumlah", "Subtotal"))
    total = 0
    for item in keranjang:
        subtotal = item['harga'] * item['jumlah']
        total += subtotal
        print("{:<20} {:<10} {:<10} {:<10}".format(item['nama'], item['harga'], item['jumlah'], subtotal))
    print(f"\n💰 Total Belanja: Rp {total:,.0f}\n")

def reset_keranjang():
    keranjang.clear()
    print("🧹 Keranjang berhasil dikosongkan.")

def kasir_menu():
    while True:
        print("\n=== APLIKASI KASIR SEDERHANA ===")
        print("1. Tambah Barang")
        print("2. Lihat Keranjang")
        print("3. Reset Keranjang")
        print("4. Keluar")
        pilihan = input("Pilih menu (1-4): ")

        if pilihan == '1':
            tambah_barang()
        elif pilihan == '2':
            tampilkan_keranjang()
        elif pilihan == '3':
            reset_keranjang()
        elif pilihan == '4':
            print("👋 Terima kasih telah menggunakan aplikasi kasir.")
            break
        else:
            print("⚠️  Pilihan tidak valid. Silakan pilih 1-4.")

# Jalankan menu
kasir_menu()

# ================================
# Aplikasi Kasir Sederhana
# Dokumentasi Teknis (Komentar per Blok)
# ================================

# List kosong untuk menyimpan item belanja (keranjang)
keranjang = []

# Fungsi untuk menambahkan barang ke keranjang
def tambah_barang():
    # Minta input dari user
    nama = input("Masukkan nama barang: ")
    try:
        harga = float(input("Masukkan harga barang: "))  # Harga dikonversi ke float
        jumlah = int(input("Masukkan jumlah barang: "))  # Jumlah dikonversi ke integer

        # Tambahkan data ke list keranjang dalam bentuk dictionary
        keranjang.append({'nama': nama, 'harga': harga, 'jumlah': jumlah})
        print(f"✅ Barang '{nama}' ditambahkan ke keranjang.")
    except ValueError:
        # Jika input tidak valid (misal huruf di kolom angka), munculkan pesan error
        print("❌ Input harga atau jumlah tidak valid. Coba lagi.")

# Fungsi untuk menampilkan isi keranjang dan total belanja
def tampilkan_keranjang():
    if not keranjang:
        print("⚠️  Keranjang masih kosong.")
        return

    # Header tampilan tabel
    print("\n📋 Daftar Belanja:")
    print("{:<20} {:<10} {:<10} {:<10}".format("Nama", "Harga", "Jumlah", "Subtotal"))

    total = 0  # Variabel total belanja
    for item in keranjang:
        # Hitung subtotal (harga x jumlah)
        subtotal = item['harga'] * item['jumlah']
        total += subtotal
        # Tampilkan item dalam format tabel
        print("{:<20} {:<10} {:<10} {:<10}".format(item['nama'], item['harga'], item['jumlah'], subtotal))

    # Tampilkan total belanja
    print(f"\n💰 Total Belanja: Rp {total:,.0f}\n")

# Fungsi untuk menghapus semua item di keranjang
def reset_keranjang():
    keranjang.clear()  # Kosongkan list keranjang
    print("🧹 Keranjang berhasil dikosongkan.")

# Fungsi utama untuk menjalankan aplikasi kasir (menu interaktif)
def kasir_menu():
    while True:
        # Tampilkan menu utama
        print("\n=== APLIKASI KASIR SEDERHANA ===")
        print("1. Tambah Barang")
        print("2. Lihat Keranjang")
        print("3. Reset Keranjang")
        print("4. Keluar")

        # Ambil pilihan dari user
        pilihan = input("Pilih menu (1-4): ")

        # Pindahkan user ke menu sesuai pilihan
        if pilihan == '1':
            tambah_barang()
        elif pilihan == '2':
            tampilkan_keranjang()
        elif pilihan == '3':
            reset_keranjang()
        elif pilihan == '4':
            print("👋 Terima kasih telah menggunakan aplikasi kasir.")
            break
        else:
            # Validasi jika user salah input
            print("⚠️  Pilihan tidak valid. Silakan pilih 1-4.")

# Jalankan program kasir saat file dieksekusi
kasir_menu()